spring:
  profiles.active: local
  datasource:
    url: jdbc:h2:tcp://localhost/./data-access
    username: sa
    password:
logging:
  level:
    org.springframework.jdbc: debug
    org.hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: trace
